apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lgv0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-lgv0@sha256:d964f0bdb7fefaefb06ccdba1666a065c5b7c213a16692007fb457c359274dfa
        name: my-nodejs
        resources: {}
status: {}
